Repository AY2223S2-CS2103-W16-1/tp, pull requests merged in 2023-03, with the labels that each got.

#67 Fix gradle shadowJar
  build.gradle
Labels: type.Task

#68 Update UG
  docs/UserGuide.md
Labels: type.Documentation

#75 Update DG on mark delivery feature implementation
  docs/DeveloperGuide.md
  docs/diagrams/MarkDeliveryActivityDiagram.puml
  docs/diagrams/MarkDeliverySequenceDiagram.puml
  docs/images/MarkDeliveryActivityDiagram.png
  docs/images/MarkDeliverySequenceDiagram.png
Labels: type.Documentation

#78 Update DG to include ViewCommand implementation
  docs/DeveloperGuide.md
  docs/diagrams/MarkDeliverySequenceDiagram.puml
  docs/diagrams/ViewCommandSequenceDiagram.puml
  docs/images/ViewCommandSequenceDiagram.png
  src/main/java/bookopedia/logic/commands/ViewCommand.java
Labels: type.Documentation, priority.High

#81 Bug fix: Edit command resets person's delivery status + attempts
  src/main/java/bookopedia/logic/commands/EditCommand.java
  src/main/java/bookopedia/logic/parser/AddCommandParser.java
  src/main/java/bookopedia/model/person/Person.java
  src/main/java/bookopedia/model/util/SampleDataUtil.java
Labels: type.Bug, priority.High

#91 Add return delivery status
  src/main/java/bookopedia/logic/commands/MarkCommand.java
  src/main/java/bookopedia/model/DeliveryStatus.java
  src/main/java/bookopedia/storage/JsonAdaptedPerson.java
  src/main/resources/view/DarkTheme.css
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/bookopedia/logic/commands/MarkCommandTest.java
  src/test/java/bookopedia/logic/commands/SortCommandTest.java
  src/test/java/bookopedia/logic/parser/MarkCommandParserTest.java
  src/test/java/bookopedia/model/AddressBookTest.java
  src/test/java/bookopedia/model/ModelManagerTest.java
  src/test/java/bookopedia/storage/JsonAdaptedPersonTest.java
  src/test/java/bookopedia/testutil/TypicalIndexes.java
  src/test/java/bookopedia/testutil/TypicalPersons.java
Labels: type.Enhancement, priority.Medium

#93 Lock marking of done deliveries
  src/main/java/bookopedia/logic/commands/MarkCommand.java
  src/test/java/bookopedia/logic/commands/MarkCommandTest.java
Labels: type.Bug, priority.High

#95 Update User Guide for mark deliveries
  docs/UserGuide.md
  docs/images/delivery_statuses.png
Labels: type.Documentation, priority.High
